<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class FacultySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('faculties')->insert([
            ['university_id' => 1, 'name' => '経営学部'],
            ['university_id' => 1, 'name' => '経済学部'],
            ['university_id' => 1, 'name' => '法学部'],
            ['university_id' => 1, 'name' => '現代中国学部'],
            ['university_id' => 1, 'name' => '国際コミニュケーション学部'],
            ['university_id' => 1, 'name' => '文学部'],
            ['university_id' => 1, 'name' => '地域政策学部'],
            ['university_id' => 1, 'name' => '短期大学部'],
            ['university_id' => 2, 'name' => '経営学部'],
            ['university_id' => 2, 'name' => '経済学部'],
            ['university_id' => 2, 'name' => '理工学部'],
            ['university_id' => 2, 'name' => '外国語学部'],
            ['university_id' => 2, 'name' => '都市情報学部'],
            ['university_id' => 3, 'name' => '経営学部'],
            ['university_id' => 3, 'name' => '経済学部'],
            ['university_id' => 3, 'name' => '法学部'],
            ['university_id' => 3, 'name' => '文学部'],
            ['university_id' => 3, 'name' => '心理学部'],
            ['university_id' => 3, 'name' => '総合政策学部'],
            ['university_id' => 3, 'name' => '薬学部'],
            ['university_id' => 4, 'name' => '理学部'],
            ['university_id' => 4, 'name' => '経済学部'],
            ['university_id' => 4, 'name' => '法学部'],
            ['university_id' => 4, 'name' => '文学部'],
            ['university_id' => 4, 'name' => '医学部'],
            ['university_id' => 4, 'name' => '農学部'],
            ['university_id' => 4, 'name' => '工学部'],
            ['university_id' => 5, 'name' => '経営部'],
            ['university_id' => 5, 'name' => '情報科学部'],
            ['university_id' => 5, 'name' => '工学部'],
            ['university_id' => 6, 'name' => '文学部'],
            ['university_id' => 6, 'name' => '国際学部'],
            ['university_id' => 6, 'name' => '心理学部'],
            ['university_id' => 6, 'name' => '現代社会学部'],
            ['university_id' => 6, 'name' => '法学部'],
            ['university_id' => 6, 'name' => '総合政策学部'],
            ['university_id' => 6, 'name' => '経済学部'],
            ['university_id' => 6, 'name' => '経営学部'],
            ['university_id' => 6, 'name' => '工学部'],
            ['university_id' => 6, 'name' => 'スポーツ科学部'],
            ['university_id' => 7, 'name' => '社会福祉学部'],
            ['university_id' => 7, 'name' => '文学部'],
            ['university_id' => 8, 'name' => '工学部'],
            ['university_id' => 9, 'name' => '人文学部'],
            ['university_id' => 9, 'name' => '外国語学部'],
            ['university_id' => 9, 'name' => '経済学部'],
            ['university_id' => 9, 'name' => '経営学部'],
            ['university_id' => 9, 'name' => '法学部'],
            ['university_id' => 9, 'name' => '総合政策学部'],
            ['university_id' => 9, 'name' => '理工学部'],
            ['university_id' => 9, 'name' => '国際教養学部'],
            ['university_id' => 10, 'name' => '医学部'],
            ['university_id' => 10, 'name' => '薬学部'],
            ['university_id' => 10, 'name' => '経済学部'],
            ['university_id' => 10, 'name' => '人文社会学部'],
            ['university_id' => 10, 'name' => '芸術工学部'],
            ['university_id' => 10, 'name' => '看護学部'],
            ['university_id' => 10, 'name' => '総合生命理学部'],
            ['university_id' => 10, 'name' => 'データサイエンス学部'],
            ['university_id' => 11, 'name' => '経済学部'],
            ['university_id' => 11, 'name' => '現代社会学部'],
            ['university_id' => 11, 'name' => '商学部'],
            ['university_id' => 11, 'name' => '経営学部'],
            ['university_id' => 11, 'name' => '法学部'],
            ['university_id' => 11, 'name' => '外国語学部'],
            ['university_id' => 11, 'name' => 'スポーツ健康学部'],
            ['university_id' => 11, 'name' => '国際文化学部'],
            ['university_id' => 11, 'name' => 'リハビリテーション学部'],
            ['university_id' => 12, 'name' => '工学部'],
            ['university_id' => 12, 'name' => '建築学部'],
            ['university_id' => 12, 'name' => '情報学部'],
            ['university_id' => 12, 'name' => '教養部'],
            ['university_id' => 13, 'name' => '経営学部'],
            ['university_id' => 13, 'name' => '教育学部'],
            ['university_id' => 13, 'name' => '人間健康学部'],
            ['university_id' => 14, 'name' => '生活科学部'],
            ['university_id' => 14, 'name' => '外国語学部'],
            ['university_id' => 14, 'name' => '人間関係学部'],
            ['university_id' => 14, 'name' => '情報社会学部'],
            ['university_id' => 14, 'name' => '現代マネイジメント学部'],
            ['university_id' => 14, 'name' => '教育学部'],
            ['university_id' => 14, 'name' => '看護学部'],
            ['university_id' => 15, 'name' => '文学部'],
            ['university_id' => 15, 'name' => '生活環境学部'],
            ['university_id' => 15, 'name' => '国際情報学部'],
            ['university_id' => 15, 'name' => '人間科学部'],
            ['university_id' => 15, 'name' => '薬学部'],
            ['university_id' => 15, 'name' => '看護学部'],
        ]);
    }
}
